/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedVaultRouteImport } from './routes/_authenticated/vault'
import { Route as AuthenticatedSopsRouteImport } from './routes/_authenticated/sops'
import { Route as AuthenticatedMyDriveConnectionRouteImport } from './routes/_authenticated/my-drive-connection'
import { Route as AuthenticatedMissionsRouteImport } from './routes/_authenticated/missions'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedKnowledgeConnectionsRouteImport } from './routes/_authenticated/knowledge-connections'
import { Route as AuthenticatedKatanaRouteImport } from './routes/_authenticated/katana'
import { Route as AuthenticatedHqRouteImport } from './routes/_authenticated/hq'
import { Route as AuthenticatedFounding100RouteImport } from './routes/_authenticated/founding-100'
import { Route as AuthenticatedEngineRouteImport } from './routes/_authenticated/engine'
import { Route as AuthenticatedCouncilRouteImport } from './routes/_authenticated/council'
import { Route as AuthenticatedCommitteeRouteImport } from './routes/_authenticated/committee'
import { Route as AuthenticatedAssetsRouteImport } from './routes/_authenticated/assets'
import { Route as ApiVoiceTtsRouteImport } from './routes/api/voice/tts'
import { Route as ApiVoiceSttRouteImport } from './routes/api/voice/stt'
import { Route as AuthenticatedSopsSopIdRouteImport } from './routes/_authenticated/sops.$sopId'
import { Route as AuthenticatedOfficeExecRouteImport } from './routes/_authenticated/office.$exec'
import { Route as AuthenticatedMissionsNewRouteImport } from './routes/_authenticated/missions.new'
import { Route as AuthenticatedMissionsMissionIdRouteImport } from './routes/_authenticated/missions.$missionId'
import { Route as AuthenticatedCommitteeCalibrationRouteImport } from './routes/_authenticated/committee.calibration'
import { Route as AuthenticatedCommitteeReviewIdRouteImport } from './routes/_authenticated/committee.$reviewId'
import { Route as AuthenticatedOfficeExecIndexRouteImport } from './routes/_authenticated/office.$exec.index'
import { Route as ApiPublicHooksKatanaRunnerRouteImport } from './routes/api/public/hooks/katana-runner'
import { Route as AuthenticatedOfficeExecThreadIdRouteImport } from './routes/_authenticated/office.$exec.$threadId'
import { Route as ApiPublicGoogleOauthCallbackRouteImport } from './routes/api/public/google/oauth/callback'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVaultRoute = AuthenticatedVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSopsRoute = AuthenticatedSopsRouteImport.update({
  id: '/sops',
  path: '/sops',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyDriveConnectionRoute =
  AuthenticatedMyDriveConnectionRouteImport.update({
    id: '/my-drive-connection',
    path: '/my-drive-connection',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMissionsRoute = AuthenticatedMissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKnowledgeConnectionsRoute =
  AuthenticatedKnowledgeConnectionsRouteImport.update({
    id: '/knowledge-connections',
    path: '/knowledge-connections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKatanaRoute = AuthenticatedKatanaRouteImport.update({
  id: '/katana',
  path: '/katana',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHqRoute = AuthenticatedHqRouteImport.update({
  id: '/hq',
  path: '/hq',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFounding100Route =
  AuthenticatedFounding100RouteImport.update({
    id: '/founding-100',
    path: '/founding-100',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEngineRoute = AuthenticatedEngineRouteImport.update({
  id: '/engine',
  path: '/engine',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCouncilRoute = AuthenticatedCouncilRouteImport.update({
  id: '/council',
  path: '/council',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommitteeRoute = AuthenticatedCommitteeRouteImport.update({
  id: '/committee',
  path: '/committee',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssetsRoute = AuthenticatedAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiVoiceTtsRoute = ApiVoiceTtsRouteImport.update({
  id: '/api/voice/tts',
  path: '/api/voice/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoiceSttRoute = ApiVoiceSttRouteImport.update({
  id: '/api/voice/stt',
  path: '/api/voice/stt',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSopsSopIdRoute = AuthenticatedSopsSopIdRouteImport.update({
  id: '/$sopId',
  path: '/$sopId',
  getParentRoute: () => AuthenticatedSopsRoute,
} as any)
const AuthenticatedOfficeExecRoute = AuthenticatedOfficeExecRouteImport.update({
  id: '/office/$exec',
  path: '/office/$exec',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMissionsNewRoute =
  AuthenticatedMissionsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedMissionsRoute,
  } as any)
const AuthenticatedMissionsMissionIdRoute =
  AuthenticatedMissionsMissionIdRouteImport.update({
    id: '/$missionId',
    path: '/$missionId',
    getParentRoute: () => AuthenticatedMissionsRoute,
  } as any)
const AuthenticatedCommitteeCalibrationRoute =
  AuthenticatedCommitteeCalibrationRouteImport.update({
    id: '/calibration',
    path: '/calibration',
    getParentRoute: () => AuthenticatedCommitteeRoute,
  } as any)
const AuthenticatedCommitteeReviewIdRoute =
  AuthenticatedCommitteeReviewIdRouteImport.update({
    id: '/$reviewId',
    path: '/$reviewId',
    getParentRoute: () => AuthenticatedCommitteeRoute,
  } as any)
const AuthenticatedOfficeExecIndexRoute =
  AuthenticatedOfficeExecIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOfficeExecRoute,
  } as any)
const ApiPublicHooksKatanaRunnerRoute =
  ApiPublicHooksKatanaRunnerRouteImport.update({
    id: '/api/public/hooks/katana-runner',
    path: '/api/public/hooks/katana-runner',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedOfficeExecThreadIdRoute =
  AuthenticatedOfficeExecThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => AuthenticatedOfficeExecRoute,
  } as any)
const ApiPublicGoogleOauthCallbackRoute =
  ApiPublicGoogleOauthCallbackRouteImport.update({
    id: '/api/public/google/oauth/callback',
    path: '/api/public/google/oauth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/assets': typeof AuthenticatedAssetsRoute
  '/committee': typeof AuthenticatedCommitteeRouteWithChildren
  '/council': typeof AuthenticatedCouncilRoute
  '/engine': typeof AuthenticatedEngineRoute
  '/founding-100': typeof AuthenticatedFounding100Route
  '/hq': typeof AuthenticatedHqRoute
  '/katana': typeof AuthenticatedKatanaRoute
  '/knowledge-connections': typeof AuthenticatedKnowledgeConnectionsRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/missions': typeof AuthenticatedMissionsRouteWithChildren
  '/my-drive-connection': typeof AuthenticatedMyDriveConnectionRoute
  '/sops': typeof AuthenticatedSopsRouteWithChildren
  '/vault': typeof AuthenticatedVaultRoute
  '/api/chat': typeof ApiChatRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/committee/$reviewId': typeof AuthenticatedCommitteeReviewIdRoute
  '/committee/calibration': typeof AuthenticatedCommitteeCalibrationRoute
  '/missions/$missionId': typeof AuthenticatedMissionsMissionIdRoute
  '/missions/new': typeof AuthenticatedMissionsNewRoute
  '/office/$exec': typeof AuthenticatedOfficeExecRouteWithChildren
  '/sops/$sopId': typeof AuthenticatedSopsSopIdRoute
  '/api/voice/stt': typeof ApiVoiceSttRoute
  '/api/voice/tts': typeof ApiVoiceTtsRoute
  '/office/$exec/$threadId': typeof AuthenticatedOfficeExecThreadIdRoute
  '/api/public/hooks/katana-runner': typeof ApiPublicHooksKatanaRunnerRoute
  '/office/$exec/': typeof AuthenticatedOfficeExecIndexRoute
  '/api/public/google/oauth/callback': typeof ApiPublicGoogleOauthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/assets': typeof AuthenticatedAssetsRoute
  '/committee': typeof AuthenticatedCommitteeRouteWithChildren
  '/council': typeof AuthenticatedCouncilRoute
  '/engine': typeof AuthenticatedEngineRoute
  '/founding-100': typeof AuthenticatedFounding100Route
  '/hq': typeof AuthenticatedHqRoute
  '/katana': typeof AuthenticatedKatanaRoute
  '/knowledge-connections': typeof AuthenticatedKnowledgeConnectionsRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/missions': typeof AuthenticatedMissionsRouteWithChildren
  '/my-drive-connection': typeof AuthenticatedMyDriveConnectionRoute
  '/sops': typeof AuthenticatedSopsRouteWithChildren
  '/vault': typeof AuthenticatedVaultRoute
  '/api/chat': typeof ApiChatRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/committee/$reviewId': typeof AuthenticatedCommitteeReviewIdRoute
  '/committee/calibration': typeof AuthenticatedCommitteeCalibrationRoute
  '/missions/$missionId': typeof AuthenticatedMissionsMissionIdRoute
  '/missions/new': typeof AuthenticatedMissionsNewRoute
  '/sops/$sopId': typeof AuthenticatedSopsSopIdRoute
  '/api/voice/stt': typeof ApiVoiceSttRoute
  '/api/voice/tts': typeof ApiVoiceTtsRoute
  '/office/$exec/$threadId': typeof AuthenticatedOfficeExecThreadIdRoute
  '/api/public/hooks/katana-runner': typeof ApiPublicHooksKatanaRunnerRoute
  '/office/$exec': typeof AuthenticatedOfficeExecIndexRoute
  '/api/public/google/oauth/callback': typeof ApiPublicGoogleOauthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_authenticated/assets': typeof AuthenticatedAssetsRoute
  '/_authenticated/committee': typeof AuthenticatedCommitteeRouteWithChildren
  '/_authenticated/council': typeof AuthenticatedCouncilRoute
  '/_authenticated/engine': typeof AuthenticatedEngineRoute
  '/_authenticated/founding-100': typeof AuthenticatedFounding100Route
  '/_authenticated/hq': typeof AuthenticatedHqRoute
  '/_authenticated/katana': typeof AuthenticatedKatanaRoute
  '/_authenticated/knowledge-connections': typeof AuthenticatedKnowledgeConnectionsRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/missions': typeof AuthenticatedMissionsRouteWithChildren
  '/_authenticated/my-drive-connection': typeof AuthenticatedMyDriveConnectionRoute
  '/_authenticated/sops': typeof AuthenticatedSopsRouteWithChildren
  '/_authenticated/vault': typeof AuthenticatedVaultRoute
  '/api/chat': typeof ApiChatRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/committee/$reviewId': typeof AuthenticatedCommitteeReviewIdRoute
  '/_authenticated/committee/calibration': typeof AuthenticatedCommitteeCalibrationRoute
  '/_authenticated/missions/$missionId': typeof AuthenticatedMissionsMissionIdRoute
  '/_authenticated/missions/new': typeof AuthenticatedMissionsNewRoute
  '/_authenticated/office/$exec': typeof AuthenticatedOfficeExecRouteWithChildren
  '/_authenticated/sops/$sopId': typeof AuthenticatedSopsSopIdRoute
  '/api/voice/stt': typeof ApiVoiceSttRoute
  '/api/voice/tts': typeof ApiVoiceTtsRoute
  '/_authenticated/office/$exec/$threadId': typeof AuthenticatedOfficeExecThreadIdRoute
  '/api/public/hooks/katana-runner': typeof ApiPublicHooksKatanaRunnerRoute
  '/_authenticated/office/$exec/': typeof AuthenticatedOfficeExecIndexRoute
  '/api/public/google/oauth/callback': typeof ApiPublicGoogleOauthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/assets'
    | '/committee'
    | '/council'
    | '/engine'
    | '/founding-100'
    | '/hq'
    | '/katana'
    | '/knowledge-connections'
    | '/library'
    | '/missions'
    | '/my-drive-connection'
    | '/sops'
    | '/vault'
    | '/api/chat'
    | '/auth/callback'
    | '/committee/$reviewId'
    | '/committee/calibration'
    | '/missions/$missionId'
    | '/missions/new'
    | '/office/$exec'
    | '/sops/$sopId'
    | '/api/voice/stt'
    | '/api/voice/tts'
    | '/office/$exec/$threadId'
    | '/api/public/hooks/katana-runner'
    | '/office/$exec/'
    | '/api/public/google/oauth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/assets'
    | '/committee'
    | '/council'
    | '/engine'
    | '/founding-100'
    | '/hq'
    | '/katana'
    | '/knowledge-connections'
    | '/library'
    | '/missions'
    | '/my-drive-connection'
    | '/sops'
    | '/vault'
    | '/api/chat'
    | '/auth/callback'
    | '/committee/$reviewId'
    | '/committee/calibration'
    | '/missions/$missionId'
    | '/missions/new'
    | '/sops/$sopId'
    | '/api/voice/stt'
    | '/api/voice/tts'
    | '/office/$exec/$threadId'
    | '/api/public/hooks/katana-runner'
    | '/office/$exec'
    | '/api/public/google/oauth/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/assets'
    | '/_authenticated/committee'
    | '/_authenticated/council'
    | '/_authenticated/engine'
    | '/_authenticated/founding-100'
    | '/_authenticated/hq'
    | '/_authenticated/katana'
    | '/_authenticated/knowledge-connections'
    | '/_authenticated/library'
    | '/_authenticated/missions'
    | '/_authenticated/my-drive-connection'
    | '/_authenticated/sops'
    | '/_authenticated/vault'
    | '/api/chat'
    | '/auth/callback'
    | '/_authenticated/committee/$reviewId'
    | '/_authenticated/committee/calibration'
    | '/_authenticated/missions/$missionId'
    | '/_authenticated/missions/new'
    | '/_authenticated/office/$exec'
    | '/_authenticated/sops/$sopId'
    | '/api/voice/stt'
    | '/api/voice/tts'
    | '/_authenticated/office/$exec/$threadId'
    | '/api/public/hooks/katana-runner'
    | '/_authenticated/office/$exec/'
    | '/api/public/google/oauth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  ApiVoiceSttRoute: typeof ApiVoiceSttRoute
  ApiVoiceTtsRoute: typeof ApiVoiceTtsRoute
  ApiPublicHooksKatanaRunnerRoute: typeof ApiPublicHooksKatanaRunnerRoute
  ApiPublicGoogleOauthCallbackRoute: typeof ApiPublicGoogleOauthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vault': {
      id: '/_authenticated/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof AuthenticatedVaultRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sops': {
      id: '/_authenticated/sops'
      path: '/sops'
      fullPath: '/sops'
      preLoaderRoute: typeof AuthenticatedSopsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-drive-connection': {
      id: '/_authenticated/my-drive-connection'
      path: '/my-drive-connection'
      fullPath: '/my-drive-connection'
      preLoaderRoute: typeof AuthenticatedMyDriveConnectionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/missions': {
      id: '/_authenticated/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof AuthenticatedMissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge-connections': {
      id: '/_authenticated/knowledge-connections'
      path: '/knowledge-connections'
      fullPath: '/knowledge-connections'
      preLoaderRoute: typeof AuthenticatedKnowledgeConnectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/katana': {
      id: '/_authenticated/katana'
      path: '/katana'
      fullPath: '/katana'
      preLoaderRoute: typeof AuthenticatedKatanaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hq': {
      id: '/_authenticated/hq'
      path: '/hq'
      fullPath: '/hq'
      preLoaderRoute: typeof AuthenticatedHqRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/founding-100': {
      id: '/_authenticated/founding-100'
      path: '/founding-100'
      fullPath: '/founding-100'
      preLoaderRoute: typeof AuthenticatedFounding100RouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/engine': {
      id: '/_authenticated/engine'
      path: '/engine'
      fullPath: '/engine'
      preLoaderRoute: typeof AuthenticatedEngineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/council': {
      id: '/_authenticated/council'
      path: '/council'
      fullPath: '/council'
      preLoaderRoute: typeof AuthenticatedCouncilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/committee': {
      id: '/_authenticated/committee'
      path: '/committee'
      fullPath: '/committee'
      preLoaderRoute: typeof AuthenticatedCommitteeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assets': {
      id: '/_authenticated/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AuthenticatedAssetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/voice/tts': {
      id: '/api/voice/tts'
      path: '/api/voice/tts'
      fullPath: '/api/voice/tts'
      preLoaderRoute: typeof ApiVoiceTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice/stt': {
      id: '/api/voice/stt'
      path: '/api/voice/stt'
      fullPath: '/api/voice/stt'
      preLoaderRoute: typeof ApiVoiceSttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sops/$sopId': {
      id: '/_authenticated/sops/$sopId'
      path: '/$sopId'
      fullPath: '/sops/$sopId'
      preLoaderRoute: typeof AuthenticatedSopsSopIdRouteImport
      parentRoute: typeof AuthenticatedSopsRoute
    }
    '/_authenticated/office/$exec': {
      id: '/_authenticated/office/$exec'
      path: '/office/$exec'
      fullPath: '/office/$exec'
      preLoaderRoute: typeof AuthenticatedOfficeExecRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/missions/new': {
      id: '/_authenticated/missions/new'
      path: '/new'
      fullPath: '/missions/new'
      preLoaderRoute: typeof AuthenticatedMissionsNewRouteImport
      parentRoute: typeof AuthenticatedMissionsRoute
    }
    '/_authenticated/missions/$missionId': {
      id: '/_authenticated/missions/$missionId'
      path: '/$missionId'
      fullPath: '/missions/$missionId'
      preLoaderRoute: typeof AuthenticatedMissionsMissionIdRouteImport
      parentRoute: typeof AuthenticatedMissionsRoute
    }
    '/_authenticated/committee/calibration': {
      id: '/_authenticated/committee/calibration'
      path: '/calibration'
      fullPath: '/committee/calibration'
      preLoaderRoute: typeof AuthenticatedCommitteeCalibrationRouteImport
      parentRoute: typeof AuthenticatedCommitteeRoute
    }
    '/_authenticated/committee/$reviewId': {
      id: '/_authenticated/committee/$reviewId'
      path: '/$reviewId'
      fullPath: '/committee/$reviewId'
      preLoaderRoute: typeof AuthenticatedCommitteeReviewIdRouteImport
      parentRoute: typeof AuthenticatedCommitteeRoute
    }
    '/_authenticated/office/$exec/': {
      id: '/_authenticated/office/$exec/'
      path: '/'
      fullPath: '/office/$exec/'
      preLoaderRoute: typeof AuthenticatedOfficeExecIndexRouteImport
      parentRoute: typeof AuthenticatedOfficeExecRoute
    }
    '/api/public/hooks/katana-runner': {
      id: '/api/public/hooks/katana-runner'
      path: '/api/public/hooks/katana-runner'
      fullPath: '/api/public/hooks/katana-runner'
      preLoaderRoute: typeof ApiPublicHooksKatanaRunnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/office/$exec/$threadId': {
      id: '/_authenticated/office/$exec/$threadId'
      path: '/$threadId'
      fullPath: '/office/$exec/$threadId'
      preLoaderRoute: typeof AuthenticatedOfficeExecThreadIdRouteImport
      parentRoute: typeof AuthenticatedOfficeExecRoute
    }
    '/api/public/google/oauth/callback': {
      id: '/api/public/google/oauth/callback'
      path: '/api/public/google/oauth/callback'
      fullPath: '/api/public/google/oauth/callback'
      preLoaderRoute: typeof ApiPublicGoogleOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedCommitteeRouteChildren {
  AuthenticatedCommitteeReviewIdRoute: typeof AuthenticatedCommitteeReviewIdRoute
  AuthenticatedCommitteeCalibrationRoute: typeof AuthenticatedCommitteeCalibrationRoute
}

const AuthenticatedCommitteeRouteChildren: AuthenticatedCommitteeRouteChildren =
  {
    AuthenticatedCommitteeReviewIdRoute: AuthenticatedCommitteeReviewIdRoute,
    AuthenticatedCommitteeCalibrationRoute:
      AuthenticatedCommitteeCalibrationRoute,
  }

const AuthenticatedCommitteeRouteWithChildren =
  AuthenticatedCommitteeRoute._addFileChildren(
    AuthenticatedCommitteeRouteChildren,
  )

interface AuthenticatedMissionsRouteChildren {
  AuthenticatedMissionsMissionIdRoute: typeof AuthenticatedMissionsMissionIdRoute
  AuthenticatedMissionsNewRoute: typeof AuthenticatedMissionsNewRoute
}

const AuthenticatedMissionsRouteChildren: AuthenticatedMissionsRouteChildren = {
  AuthenticatedMissionsMissionIdRoute: AuthenticatedMissionsMissionIdRoute,
  AuthenticatedMissionsNewRoute: AuthenticatedMissionsNewRoute,
}

const AuthenticatedMissionsRouteWithChildren =
  AuthenticatedMissionsRoute._addFileChildren(
    AuthenticatedMissionsRouteChildren,
  )

interface AuthenticatedSopsRouteChildren {
  AuthenticatedSopsSopIdRoute: typeof AuthenticatedSopsSopIdRoute
}

const AuthenticatedSopsRouteChildren: AuthenticatedSopsRouteChildren = {
  AuthenticatedSopsSopIdRoute: AuthenticatedSopsSopIdRoute,
}

const AuthenticatedSopsRouteWithChildren =
  AuthenticatedSopsRoute._addFileChildren(AuthenticatedSopsRouteChildren)

interface AuthenticatedOfficeExecRouteChildren {
  AuthenticatedOfficeExecThreadIdRoute: typeof AuthenticatedOfficeExecThreadIdRoute
  AuthenticatedOfficeExecIndexRoute: typeof AuthenticatedOfficeExecIndexRoute
}

const AuthenticatedOfficeExecRouteChildren: AuthenticatedOfficeExecRouteChildren =
  {
    AuthenticatedOfficeExecThreadIdRoute: AuthenticatedOfficeExecThreadIdRoute,
    AuthenticatedOfficeExecIndexRoute: AuthenticatedOfficeExecIndexRoute,
  }

const AuthenticatedOfficeExecRouteWithChildren =
  AuthenticatedOfficeExecRoute._addFileChildren(
    AuthenticatedOfficeExecRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAssetsRoute: typeof AuthenticatedAssetsRoute
  AuthenticatedCommitteeRoute: typeof AuthenticatedCommitteeRouteWithChildren
  AuthenticatedCouncilRoute: typeof AuthenticatedCouncilRoute
  AuthenticatedEngineRoute: typeof AuthenticatedEngineRoute
  AuthenticatedFounding100Route: typeof AuthenticatedFounding100Route
  AuthenticatedHqRoute: typeof AuthenticatedHqRoute
  AuthenticatedKatanaRoute: typeof AuthenticatedKatanaRoute
  AuthenticatedKnowledgeConnectionsRoute: typeof AuthenticatedKnowledgeConnectionsRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedMissionsRoute: typeof AuthenticatedMissionsRouteWithChildren
  AuthenticatedMyDriveConnectionRoute: typeof AuthenticatedMyDriveConnectionRoute
  AuthenticatedSopsRoute: typeof AuthenticatedSopsRouteWithChildren
  AuthenticatedVaultRoute: typeof AuthenticatedVaultRoute
  AuthenticatedOfficeExecRoute: typeof AuthenticatedOfficeExecRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAssetsRoute: AuthenticatedAssetsRoute,
  AuthenticatedCommitteeRoute: AuthenticatedCommitteeRouteWithChildren,
  AuthenticatedCouncilRoute: AuthenticatedCouncilRoute,
  AuthenticatedEngineRoute: AuthenticatedEngineRoute,
  AuthenticatedFounding100Route: AuthenticatedFounding100Route,
  AuthenticatedHqRoute: AuthenticatedHqRoute,
  AuthenticatedKatanaRoute: AuthenticatedKatanaRoute,
  AuthenticatedKnowledgeConnectionsRoute:
    AuthenticatedKnowledgeConnectionsRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedMissionsRoute: AuthenticatedMissionsRouteWithChildren,
  AuthenticatedMyDriveConnectionRoute: AuthenticatedMyDriveConnectionRoute,
  AuthenticatedSopsRoute: AuthenticatedSopsRouteWithChildren,
  AuthenticatedVaultRoute: AuthenticatedVaultRoute,
  AuthenticatedOfficeExecRoute: AuthenticatedOfficeExecRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  ApiVoiceSttRoute: ApiVoiceSttRoute,
  ApiVoiceTtsRoute: ApiVoiceTtsRoute,
  ApiPublicHooksKatanaRunnerRoute: ApiPublicHooksKatanaRunnerRoute,
  ApiPublicGoogleOauthCallbackRoute: ApiPublicGoogleOauthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
